name: Application Test and Deploy Workflow

on:
  push:
    branches:
      - main

env:
  REPO_NAME: express-deploy-example
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: us-west1
  REPOSITORY: express-deploy-example
  REGION: us-west1
  SERVICE: express-deploy-example

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Jest framework
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run test

  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"

    needs: test
    name: Build and Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SA_JSON }}

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CLOUD_RUN_SA_JSON }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          region: ${{ env.GAR_LOCATION }}
          service: ${{ env.SERVICE }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
