name: Application Test and Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubutnu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test using Jest framework
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run test